language: android
dist: trusty

android:
  components:
    - build-tools-29.0.2
    - android-29

before_install:
  - yes | sdkmanager "platforms;android-29"

script:
  - ./gradlew build
  #TODO: When all tests are passing, CI should also execute them.
  #- ./gradlew connectedCheck