#https://github.com/marketplace/actions/android-emulator-runner
name: Build nightly
on: [ push ]

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Assemble nighlty APK
        shell: bash
        run: |
          echo ${NIGHTLY_STORE_FILE} | base64 -d > KEY_NIGHTLY.jks
          ./gradlew assembleNightly -Dnightly_store_file=KEY_NIGHTLY.jks -Dnightly_store_password="${NIGHTLY_STORE_PASSWORD}" -Dnightly_key_alias="${NIGHTLY_KEY_ALIAS}" -Dnightly_key_password="${NIGHTLY_STORE_PASSWORD}"
        env:
          NIGHTLY_STORE_FILE: ${{ secrets.NIGHTLY_STORE_FILE }}
          NIGHTLY_STORE_PASSWORD: ${{ secrets.NIGHTLY_STORE_PASSWORD }}
          NIGHTLY_KEY_ALIAS: ${{ secrets.NIGHTLY_KEY_ALIAS }}

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: OpenTracks-nightly.apk
          path: ./build/outputs/apk/nightly/OpenTracks-nightly.apk
          retention-days: 7

