#https://github.com/marketplace/actions/android-emulator-runner
name: Build APK
on:
  push

jobs:
  apk-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Assemble APK
        shell: bash
        run: |
          echo ${NIGHTLY_STORE_FILE} | base64 -d > KEY_NIGHTLY.jks
          ./gradlew assembleNightly -Dnightly_store_file=KEY_NIGHTLY.jks -Dnightly_store_password="${NIGHTLY_STORE_PASSWORD}" -Dnightly_key_alias="${NIGHTLY_KEY_ALIAS}" -Dnightly_key_password="${NIGHTLY_STORE_PASSWORD}"
        env:
          NIGHTLY_STORE_FILE: ${{ secrets.NIGHTLY_STORE_FILE }}
          NIGHTLY_STORE_PASSWORD: ${{ secrets.NIGHTLY_STORE_PASSWORD }}
          NIGHTLY_KEY_ALIAS: ${{ secrets.NIGHTLY_KEY_ALIAS }}

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: OpenTracks-APK.apk
          path: ./build/outputs/apk/nightly/*.apk
          retention-days: 7

